### ISSUE TITLE
Where is the templates folder and how i can add new template

### ISSUE THREAD

**Issue by winandiaris** [app-generator/django-adminlte_p#1]
Where is the templates folder and how i can add a new template?
I found the template is targeting directly the library directory on the env

Thanks

**Comment by app-generator** [comment]
Hello @winandiaris 

Thank you for using our products. 

First, this project will not be updated anymore. The AdminLTE theme is managed under this starter: 

https://github.com/app-generator/django-adminlte

In order to extend the [AdminLTE Theme](https://github.com/app-generator/django-admin-adminlte) you need the following updates:

- Create inside your app a new `template` folder that should mirror the library [Template](https://github.com/app-generator/django-admin-adminlte/tree/main/admin_adminlte/templates) folder
- Extend the [footer](https://github.com/app-generator/django-admin-adminlte/blob/main/admin_adminlte/templates/includes/footer.html) for instance
  - create a new file locally: `your_app\templates\includes\footer.html`
  - update the content of `footer` component

At this point, the footer component is extended but Django needs to be configured to use the new `template` folder.

> Here is the configuration for `home` APP:

```python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'home/templates'],   # <-- NEW
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
````

Let us know if you need more information or further assistance.
If needed, we can [fork a sample project](https://github.com/app-generator/django-adminlte/generate) and assist you with the code directly.  
   
P.S. Sorry for the missing DOCS, but we are migrating from GitBook to Docusaurus and the edits are frozen. The new docs should be LIVE at the end of this week.

https://docs.appseed.us
🚀🚀

**Comment by winandiaris** [comment]
Thanks for answering, your product is very good if not the best.

I have a backend with Django 4, and I want to pair it with the latest bootstrap.
I would like to ask if any of your products have more complete prebuild data or Django models/apps like authentication/authorization, table, and form data with ajax, galleries, and templates which can also be applied to Django admin.

If on a paid plan, how much does it cost?

I use adminlte because you implement Django 4 in it and it has more complete documentation and widgets in the original sources.

**Comment by app-generator** [comment]
Hello @winandiaris 

Ty for the kind words. 

Just to give you an insight, we are migrating all products (Django, Flask...) to a similar theme-able pattern, CI/CD included, page compression in production, and CDN support ...

These PRO kists are the first ones available: 

- Soft BS5: https://github.com/app-generator/django-soft-ui-dashboard-pro
- Berry BS5: https://github.com/app-generator/django-berry-dashboard-pro
- Argon2 BS5: https://github.com/app-generator/django-argon-dashboard2-pro
- Material2 BS5: https://github.com/app-generator/django-material-dashboard2-pro

Regarding the pricing, the personal license starts from $89 and goes up to $299/349 for a Company License (unlimited projects)

The good news might be the 75% discount that applies to all products and licenses until 15.JAN. 

https://appseed.us/discounts/ - `more info here`

Let us know if you need further assistance. 
🚀🚀

**Comment by winandiaris** [comment]
I have tried as you suggest, but the static files are not generated. do I need to put static files in a public folder / templates folder?

And how to make one template folder handle all apps templates `([BASE_DIR / 'home/templates'])` as far as I know you used TEMPLATE_DIR for older versions of appseed

I plan to deploy only using docker, not using render

I've forked a sample project at https://github.com/winandiaris/arisapp

**Comment by app-generator** [comment]
Hello @winandiaris 

Let's move the issue to the real project and try to solve it: 

https://github.com/app-generator/django-adminlte

We need:

- The Target Platform
- The Docker constraints 

See u there

🚀🚀
